package common;

import java.io.Serializable;

public enum MsgEnum implements Serializable {
	LOGIN, LOGIN_ERROR,
	LOGOUT, ADD_REQUEST,ADD_FILES,SEND_ID_OF_REQUEST_TO_CLIENT,
	GET_REQUESTS_BY_ID_STARTED,GET_REQUESTS_BY_ID_NOSTARTED,
	SEND_RS_NOT_STARTED_TO_CLIENT, SEND_RS_STARTED_TO_CLIENT, 
	VIEW_MESSAGES,SEND_MESSAGES_TO_CLIENT, VIEW_EMPLOYEES,VIEW_PROCESSES,VIEW_ACTIONS,VIEW_PROCESSES_TO_BE_DETERMINED,VIEW_REQUEST,ADD_EV_REPORT;
}
